[package]
name = "po_api_all"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.7.0"
rusqlite = { version= "0.31.0", features = ["bundled"] }
serde = {version = "1.0.203", features = ["serde_derive"]}
serde_json = "1.0.117"
